Sort contacts, Remove Remark command
AY2324S1-CS2103T-F12-4/tp pull request #99
Opened 2023-10-26 12:47 UTC by LoMaply

Person list sorted automatically by last contacted date
Removed remark command since Remarks are implemented with `addc` and `editc`
Update docs and diagrams

2023-10-26 12:52 UTC, LoMaply commented
Maybe wait for #93 and #96 to be merged first?

2023-10-26 15:24 UTC, howenc commented
Uh, editing remark is not supported through `editc`

2023-10-27 02:21 UTC, howenc requested changes
Some changes are needed for the tests that you change if im not wrong

2023-10-27 06:34 UTC, howenc approved these changes

2023-10-27 06:34 UTC, merged